# Generated by Django 6.0.4 on 2026-04-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.parent'),
        ),
    ]
