# Generated by Django 6.0.4 on 2026-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='DkafDx8Mmewx1Yio9lj2Q4JnGHuuPivN', editable=False, max_length=32, unique=True),
        ),
    ]
